import '../src/style.css';
import { createLightingScene } from '../src/scene.ts';
import { createControls } from '../src/controls.ts';
import { createEditor } from '../src/editor.ts';
import { createTextItem } from '../src/project.ts';
import { glassGrid } from './glass-fixture.ts';
const host = document.querySelector<HTMLElement>('#scene')!;
const scene = createLightingScene(host);
const controls = createControls(document.querySelector('#controls')!, scene);
const editor = createEditor(document.querySelector('#editor')!, host, scene);
const refresh = () => controls.refresh();
host.addEventListener('study-change', refresh);
await scene.ready;
await scene.addItem(glassGrid());
await scene.addItem({ ...createTextItem(), text: 'GLASS', treatment: 'solid', x: 0, y: -0.17, size: 0.045, offset: 0.025 });
await scene.addItem({ ...createTextItem(), text: 'Light through color', treatment: 'flat', x: 0, y: -0.26, size: 0.025, offset: 0.01 });
scene.selectItem(null);
document.querySelectorAll<HTMLDetailsElement>('details').forEach((panel) => { panel.open = false; });
document.querySelector<HTMLElement>('#status')!.hidden = true;
if (import.meta.hot) import.meta.hot.dispose(() => { host.removeEventListener('study-change', refresh); controls.dispose(); editor.dispose(); scene.dispose(); });
